import os
import requests

api_url = os.environ.get("VIKUNJA_API_URL")
api_token = os.environ.get("VIKUNJA_API_TOKEN")

headers = {
    "Authorization": f"Bearer {api_token}",
    "Content-Type": "application/json"
}

task_id = 4
url = f"{api_url}/tasks/{task_id}"

desc = """### What Shipped:
Interactive, split-pane Spec-Diagram design system (Milestone 1: Scaffold & TDD Setup) — layout and workspace components are 100% generated by v0 (v0.dev chat rS4YBwFOaK4) and verified via Vitest.

### Milestones Completed:
1. **v0.dev Code Generation:** Successfully compiled and generated Next.js TSX Workspace components using the v0.dev API.
2. **Multi-View Spec-Editor:** Left pane contains raw YAML specs, collapsible AST explorer tree, and focused selected unit panels.
3. **Excalidraw Integration:** Right pane Dynamically embedded dynamic client-side Excalidraw white-boarding canvas.
4. **TDD GREEN:** All 3 unit tests passed successfully on Vitest.
5. **Git Push:** Committed and cleanly pushed to feature branch `feature/scaffold-and-tdd-setup`!
"""

payload = {
    "done": True,
    "description": desc
}

print(f"Updating and completing Vikunja task {task_id}...")
r = requests.post(url, headers=headers, json=payload)
print("STATUS:", r.status_code)
if r.status_code == 200:
    print("SUCCESS: Completed task on Vikunja!")
else:
    print(r.text)
